services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  # server:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
